CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    cart_id INTEGER,
    FOREIGN KEY (cart_id) REFERENCES cart (user_id) ON DELETE SET NULL
);